/**
 * Comprehensive search filter options for advanced search forms
 */

export interface FilterOption {
  label: string;
  value: string;
}

export const LOCATIONS: FilterOption[] = [
  // España
  { label: 'Madrid', value: 'Madrid' },
  { label: 'Barcelona', value: 'Barcelona' },
  { label: 'Valencia', value: 'Valencia' },
  { label: 'Bilbao', value: 'Bilbao' },
  { label: 'Sevilla', value: 'Sevilla' },
  { label: 'Málaga', value: 'Málaga' },
  { label: 'Alicante', value: 'Alicante' },
  { label: 'Murcia', value: 'Murcia' },
  { label: 'Palma de Mallorca', value: 'Palma de Mallorca' },
  { label: 'Zaragoza', value: 'Zaragoza' },
  { label: 'Córdoba', value: 'Córdoba' },
  { label: 'Granada', value: 'Granada' },
  { label: 'Valladolid', value: 'Valladolid' },
  { label: 'Toledo', value: 'Toledo' },
  { label: 'Salamanca', value: 'Salamanca' },
  { label: 'Ávila', value: 'Ávila' },
  { label: 'Segovia', value: 'Segovia' },
  { label: 'León', value: 'León' },
  { label: 'Tarragona', value: 'Tarragona' },
  { label: 'Girona', value: 'Girona' },
  { label: 'Lleida', value: 'Lleida' },
  { label: 'Castellón', value: 'Castellón' },
  { label: 'Elche', value: 'Elche' },
  { label: 'Logroño', value: 'Logroño' },
  { label: 'Pamplona', value: 'Pamplona' },
  { label: 'Vitoria', value: 'Vitoria' },
  { label: 'San Sebastián', value: 'San Sebastián' },
  { label: 'Santander', value: 'Santander' },
  { label: 'Oviedo', value: 'Oviedo' },

  // Latinoamérica
  { label: 'Buenos Aires', value: 'Buenos Aires' },
  { label: 'Córdoba (Argentina)', value: 'Córdoba, Argentina' },
  { label: 'Rosario', value: 'Rosario' },
  { label: 'Mendoza', value: 'Mendoza' },
  { label: 'La Plata', value: 'La Plata' },
  { label: 'São Paulo', value: 'São Paulo' },
  { label: 'Rio de Janeiro', value: 'Rio de Janeiro' },
  { label: 'São Paulo (SP)', value: 'São Paulo, SP' },
  { label: 'Brasília', value: 'Brasília' },
  { label: 'Salvador', value: 'Salvador' },
  { label: 'Fortaleza', value: 'Fortaleza' },
  { label: 'Belo Horizonte', value: 'Belo Horizonte' },
  { label: 'Manaus', value: 'Manaus' },
  { label: 'Recife', value: 'Recife' },
  { label: 'Belém', value: 'Belém' },
  { label: 'Curitiba', value: 'Curitiba' },
  { label: 'Porto Alegre', value: 'Porto Alegre' },
  { label: 'México', value: 'Ciudad de México' },
  { label: 'Guadalajara', value: 'Guadalajara' },
  { label: 'Monterrey', value: 'Monterrey' },
  { label: 'Cancún', value: 'Cancún' },
  { label: 'Querétaro', value: 'Querétaro' },
  { label: 'León', value: 'León, México' },
  { label: 'Bogotá', value: 'Bogotá' },
  { label: 'Medellín', value: 'Medellín' },
  { label: 'Cali', value: 'Cali' },
  { label: 'Barranquilla', value: 'Barranquilla' },
  { label: 'Cartagena', value: 'Cartagena' },
  { label: 'Lima', value: 'Lima' },
  { label: 'Arequipa', value: 'Arequipa' },
  { label: 'Cusco', value: 'Cusco' },
  { label: 'Santiago de Chile', value: 'Santiago de Chile' },
  { label: 'Valparaíso', value: 'Valparaíso' },
  { label: 'Concepción', value: 'Concepción' },
  { label: 'La Serena', value: 'La Serena' },
  { label: 'Caracas', value: 'Caracas' },
  { label: 'Valencia (Venezuela)', value: 'Valencia, Venezuela' },
  { label: 'Maracaibo', value: 'Maracaibo' },
  { label: 'Quito', value: 'Quito' },
  { label: 'Guayaquil', value: 'Guayaquil' },
  { label: 'Cuenca', value: 'Cuenca' },
  { label: 'San José de Costa Rica', value: 'San José, Costa Rica' },
  { label: 'San Salvador', value: 'San Salvador' },
  { label: 'Tegucigalpa', value: 'Tegucigalpa' },
  { label: 'Ciudad de Panamá', value: 'Ciudad de Panamá' },
  { label: 'La Habana', value: 'La Habana' },
  { label: 'Santo Domingo', value: 'Santo Domingo' },
  { label: 'Nassau', value: 'Nassau' },
  { label: 'Guatemala City', value: 'Guatemala City' },

  // USA
  { label: 'New York', value: 'New York' },
  { label: 'Los Angeles', value: 'Los Angeles' },
  { label: 'Chicago', value: 'Chicago' },
  { label: 'Houston', value: 'Houston' },
  { label: 'Phoenix', value: 'Phoenix' },
  { label: 'Philadelphia', value: 'Philadelphia' },
  { label: 'San Antonio', value: 'San Antonio' },
  { label: 'San Diego', value: 'San Diego' },
  { label: 'Dallas', value: 'Dallas' },
  { label: 'San Jose', value: 'San Jose' },
  { label: 'Austin', value: 'Austin' },
  { label: 'Jacksonville', value: 'Jacksonville' },
  { label: 'Fort Worth', value: 'Fort Worth' },
  { label: 'Columbus', value: 'Columbus' },
  { label: 'Charlotte', value: 'Charlotte' },
  { label: 'San Francisco', value: 'San Francisco' },
  { label: 'Indianapolis', value: 'Indianapolis' },
  { label: 'Austin', value: 'Austin, TX' },
  { label: 'Seattle', value: 'Seattle' },
  { label: 'Denver', value: 'Denver' },
  { label: 'Washington DC', value: 'Washington, DC' },
  { label: 'Boston', value: 'Boston' },
  { label: 'Miami', value: 'Miami' },
  { label: 'Atlanta', value: 'Atlanta' },
  { label: 'Las Vegas', value: 'Las Vegas' },
  { label: 'Portland', value: 'Portland' },
  { label: 'Minneapolis', value: 'Minneapolis' },
  { label: 'Raleigh', value: 'Raleigh' },
  { label: 'Detroit', value: 'Detroit' },
];

export const JOB_TITLES: FilterOption[] = [
  // Executive
  { label: 'CEO', value: 'CEO' },
  { label: 'Founder', value: 'Founder' },
  { label: 'CO-Founder', value: 'Co-Founder' },
  { label: 'President', value: 'President' },
  { label: 'Vice President', value: 'Vice President' },
  { label: 'Managing Director', value: 'Managing Director' },
  { label: 'Chief Operating Officer (COO)', value: 'COO' },
  { label: 'Chief Technology Officer (CTO)', value: 'CTO' },
  { label: 'Chief Financial Officer (CFO)', value: 'CFO' },
  { label: 'Chief Marketing Officer (CMO)', value: 'CMO' },
  { label: 'Chief Sales Officer (CSO)', value: 'CSO' },
  { label: 'Chief Product Officer (CPO)', value: 'CPO' },
  { label: 'Chief Growth Officer (CGO)', value: 'CGO' },
  { label: 'General Manager', value: 'General Manager' },
  { label: 'Executive Director', value: 'Executive Director' },

  // Management
  { label: 'Director', value: 'Director' },
  { label: 'Senior Director', value: 'Senior Director' },
  { label: 'Manager', value: 'Manager' },
  { label: 'Senior Manager', value: 'Senior Manager' },
  { label: 'Regional Manager', value: 'Regional Manager' },
  { label: 'Account Manager', value: 'Account Manager' },
  { label: 'Project Manager', value: 'Project Manager' },
  { label: 'Product Manager', value: 'Product Manager' },
  { label: 'Marketing Manager', value: 'Marketing Manager' },
  { label: 'Sales Manager', value: 'Sales Manager' },
  { label: 'Operations Manager', value: 'Operations Manager' },
  { label: 'HR Manager', value: 'HR Manager' },
  { label: 'Finance Manager', value: 'Finance Manager' },

  // Sales & Business Development
  { label: 'Business Development Manager', value: 'Business Development Manager' },
  { label: 'Sales Director', value: 'Sales Director' },
  { label: 'Head of Sales', value: 'Head of Sales' },
  { label: 'Sales Representative', value: 'Sales Representative' },
  { label: 'Account Executive', value: 'Account Executive' },
  { label: 'Territory Manager', value: 'Territory Manager' },
  { label: 'Business Development Executive', value: 'Business Development Executive' },
  { label: 'Sales Development Rep (SDR)', value: 'Sales Development Rep' },

  // Marketing
  { label: 'Head of Marketing', value: 'Head of Marketing' },
  { label: 'Marketing Director', value: 'Marketing Director' },
  { label: 'Digital Marketing Manager', value: 'Digital Marketing Manager' },
  { label: 'Content Manager', value: 'Content Manager' },
  { label: 'Brand Manager', value: 'Brand Manager' },
  { label: 'Marketing Specialist', value: 'Marketing Specialist' },
  { label: 'Social Media Manager', value: 'Social Media Manager' },
  { label: 'SEO Specialist', value: 'SEO Specialist' },
  { label: 'Growth Hacker', value: 'Growth Hacker' },
  { label: 'Marketing Consultant', value: 'Marketing Consultant' },

  // Operations
  { label: 'Head of Operations', value: 'Head of Operations' },
  { label: 'Operations Director', value: 'Operations Director' },
  { label: 'Supply Chain Manager', value: 'Supply Chain Manager' },
  { label: 'Logistics Manager', value: 'Logistics Manager' },
  { label: 'Process Improvement Manager', value: 'Process Improvement Manager' },

  // Finance
  { label: 'Controller', value: 'Controller' },
  { label: 'Treasurer', value: 'Treasurer' },
  { label: 'Accountant', value: 'Accountant' },
  { label: 'Financial Analyst', value: 'Financial Analyst' },
  { label: 'Bookkeeper', value: 'Bookkeeper' },

  // Technology
  { label: 'VP Engineering', value: 'VP Engineering' },
  { label: 'Engineering Manager', value: 'Engineering Manager' },
  { label: 'Tech Lead', value: 'Tech Lead' },
  { label: 'Software Engineer', value: 'Software Engineer' },
  { label: 'Senior Software Engineer', value: 'Senior Software Engineer' },
  { label: 'DevOps Engineer', value: 'DevOps Engineer' },
  { label: 'Data Scientist', value: 'Data Scientist' },
  { label: 'Data Analyst', value: 'Data Analyst' },
  { label: 'System Administrator', value: 'System Administrator' },

  // HR & Administration
  { label: 'Head of HR', value: 'Head of HR' },
  { label: 'HR Director', value: 'HR Director' },
  { label: 'Talent Acquisition Manager', value: 'Talent Acquisition Manager' },
  { label: 'Recruiter', value: 'Recruiter' },
  { label: 'HR Specialist', value: 'HR Specialist' },
  { label: 'Administrative Director', value: 'Administrative Director' },
  { label: 'Executive Assistant', value: 'Executive Assistant' },

  // Health & Wellness (specific for health businesses)
  { label: 'Health Coach', value: 'Health Coach' },
  { label: 'Fitness Trainer', value: 'Fitness Trainer' },
  { label: 'Personal Trainer', value: 'Personal Trainer' },
  { label: 'Yoga Instructor', value: 'Yoga Instructor' },
  { label: 'Nutritionist', value: 'Nutritionist' },
  { label: 'Clinical Director', value: 'Clinical Director' },
  { label: 'Medical Director', value: 'Medical Director' },
  { label: 'Practice Manager', value: 'Practice Manager' },
  { label: 'Ownership Interest', value: 'Ownership Interest' },
  { label: 'Owner', value: 'Owner' },
  { label: 'Proprietor', value: 'Proprietor' },
];

export const COMPANY_SIZES: FilterOption[] = [
  { label: '1-10 employees', value: '1-10' },
  { label: '10-50 employees', value: '10-50' },
  { label: '50-100 employees', value: '50-100' },
  { label: '100-500 employees', value: '100-500' },
  { label: '500-1000 employees', value: '500-1000' },
  { label: '1000-5000 employees', value: '1000-5000' },
  { label: '5000-10000 employees', value: '5000-10000' },
  { label: '10000+ employees', value: '10000+' },
  { label: 'Startup (1-50)', value: 'startup' },
  { label: 'Small Business (1-100)', value: 'small' },
  { label: 'Medium Business (100-1000)', value: 'medium' },
  { label: 'Large Enterprise (1000+)', value: 'large' },
];

export const INDUSTRIES: FilterOption[] = [
  // Health & Wellness
  { label: 'Healthcare', value: 'Healthcare' },
  { label: 'Fitness & Gym', value: 'Fitness & Gym' },
  { label: 'Yoga Studio', value: 'Yoga Studio' },
  { label: 'Personal Training', value: 'Personal Training' },
  { label: 'Nutrition & Dietetics', value: 'Nutrition & Dietetics' },
  { label: 'Mental Health / Therapy', value: 'Mental Health' },
  { label: 'Wellness Center', value: 'Wellness Center' },
  { label: 'Medical Practice', value: 'Medical Practice' },
  { label: 'Dental Practice', value: 'Dental Practice' },
  { label: 'Veterinary', value: 'Veterinary' },
  { label: 'Pharmaceutical', value: 'Pharmaceutical' },
  { label: 'Biotech', value: 'Biotech' },
  { label: 'Beauty & Spa', value: 'Beauty & Spa' },
  { label: 'Hair Salon', value: 'Hair Salon' },
  { label: 'Medical Device', value: 'Medical Device' },
  { label: 'Health Insurance', value: 'Health Insurance' },
  { label: 'Clinic', value: 'Clinic' },
  { label: 'Wellness App', value: 'Wellness App' },
  { label: 'Sports Medicine', value: 'Sports Medicine' },
  { label: 'Physical Therapy', value: 'Physical Therapy' },

  // Technology
  { label: 'Software Development', value: 'Software Development' },
  { label: 'SaaS', value: 'SaaS' },
  { label: 'Artificial Intelligence', value: 'Artificial Intelligence' },
  { label: 'Cloud Computing', value: 'Cloud Computing' },
  { label: 'Cybersecurity', value: 'Cybersecurity' },
  { label: 'Data Analytics', value: 'Data Analytics' },
  { label: 'Mobile App Development', value: 'Mobile App Development' },
  { label: 'Web Development', value: 'Web Development' },
  { label: 'IT Services', value: 'IT Services' },
  { label: 'Tech Consulting', value: 'Tech Consulting' },
  { label: 'E-commerce Platform', value: 'E-commerce Platform' },
  { label: 'Marketing Technology', value: 'Marketing Technology' },
  { label: 'FinTech', value: 'FinTech' },
  { label: 'EdTech', value: 'EdTech' },
  { label: 'Hardware', value: 'Hardware' },

  // Business Services
  { label: 'Management Consulting', value: 'Management Consulting' },
  { label: 'Accounting & Audit', value: 'Accounting & Audit' },
  { label: 'Legal Services', value: 'Legal Services' },
  { label: 'Human Resources', value: 'Human Resources' },
  { label: 'Recruitment', value: 'Recruitment' },
  { label: 'Marketing Agency', value: 'Marketing Agency' },
  { label: 'Digital Marketing Agency', value: 'Digital Marketing Agency' },
  { label: 'Advertising Agency', value: 'Advertising Agency' },
  { label: 'Creative Agency', value: 'Creative Agency' },
  { label: 'Public Relations', value: 'Public Relations' },
  { label: 'Event Management', value: 'Event Management' },
  { label: 'Business Consulting', value: 'Business Consulting' },
  { label: 'Corporate Training', value: 'Corporate Training' },
  { label: 'Executive Coaching', value: 'Executive Coaching' },

  // Finance & Investment
  { label: 'Banking', value: 'Banking' },
  { label: 'Insurance', value: 'Insurance' },
  { label: 'Investment Firm', value: 'Investment Firm' },
  { label: 'Venture Capital', value: 'Venture Capital' },
  { label: 'Private Equity', value: 'Private Equity' },
  { label: 'Real Estate', value: 'Real Estate' },
  { label: 'Construction', value: 'Construction' },
  { label: 'Engineering', value: 'Engineering' },

  // Education
  { label: 'University', value: 'University' },
  { label: 'School', value: 'School' },
  { label: 'Online Learning', value: 'Online Learning' },
  { label: 'Training Center', value: 'Training Center' },
  { label: 'Online Courses', value: 'Online Courses' },
  { label: 'Language School', value: 'Language School' },
  { label: 'tutoring', value: 'Tutoring' },

  // Retail & Consumer
  { label: 'Retail', value: 'Retail' },
  { label: 'E-commerce', value: 'E-commerce' },
  { label: 'Fashion & Apparel', value: 'Fashion & Apparel' },
  { label: 'Food & Beverage', value: 'Food & Beverage' },
  { label: 'Restaurant', value: 'Restaurant' },
  { label: 'Cafe/Coffee Shop', value: 'Cafe' },
  { label: 'Grocery Store', value: 'Grocery Store' },
  { label: 'Convenience Store', value: 'Convenience Store' },
  { label: 'Supplements Store', value: 'Supplements Store' },
  { label: 'Health Food Store', value: 'Health Food Store' },

  // Real Estate & Property
  { label: 'Real Estate Agency', value: 'Real Estate Agency' },
  { label: 'Property Management', value: 'Property Management' },
  { label: 'Hotel & Hospitality', value: 'Hotel & Hospitality' },
  { label: 'Vacation Rentals', value: 'Vacation Rentals' },
  { label: 'AirBnB Host', value: 'AirBnB Host' },

  // Transportation & Logistics
  { label: 'Transportation', value: 'Transportation' },
  { label: 'Logistics', value: 'Logistics' },
  { label: 'Uber / Rideshare', value: 'Uber / Rideshare' },
  { label: 'Delivery Service', value: 'Delivery Service' },
  { label: 'Shipping', value: 'Shipping' },
  { label: 'Automotive', value: 'Automotive' },
  { label: 'Auto Repair', value: 'Auto Repair' },
  { label: 'Car Dealership', value: 'Car Dealership' },

  // Manufacturing
  { label: 'Manufacturing', value: 'Manufacturing' },
  { label: 'Industrial Manufacturing', value: 'Industrial Manufacturing' },
  { label: 'Food Manufacturing', value: 'Food Manufacturing' },
  { label: 'Textile Manufacturing', value: 'Textile Manufacturing' },

  // Entertainment & Media
  { label: 'Entertainment', value: 'Entertainment' },
  { label: 'Media Publishing', value: 'Media Publishing' },
  { label: 'Film & Video Production', value: 'Film & Video Production' },
  { label: 'Music & Audio Production', value: 'Music & Audio Production' },
  { label: 'Gaming', value: 'Gaming' },
  { label: 'Streaming Service', value: 'Streaming Service' },
  { label: 'Social Media', value: 'Social Media' },
  { label: 'Content Creator', value: 'Content Creator' },
  { label: 'Influencer', value: 'Influencer' },
  { label: 'Podcast', value: 'Podcast' },
  { label: 'Blog/News', value: 'Blog/News' },

  // Sports & Recreation
  { label: 'Sports', value: 'Sports' },
  { label: 'Recreation Facility', value: 'Recreation Facility' },
  { label: 'Sports Management', value: 'Sports Management' },
  { label: 'Sports Team', value: 'Sports Team' },

  // Non-Profit & Government
  { label: 'Non-Profit', value: 'Non-Profit' },
  { label: 'Government', value: 'Government' },
  { label: 'Government Agency', value: 'Government Agency' },
  { label: 'NGO', value: 'NGO' },
  { label: 'Charity', value: 'Charity' },

  // Energy & Utilities
  { label: 'Energy', value: 'Energy' },
  { label: 'Utilities', value: 'Utilities' },
  { label: 'Solar Energy', value: 'Solar Energy' },
  { label: 'Renewable Energy', value: 'Renewable Energy' },
  { label: 'Oil & Gas', value: 'Oil & Gas' },

  // Agriculture
  { label: 'Agriculture', value: 'Agriculture' },
  { label: 'Farming', value: 'Farming' },
  { label: 'Organic Farming', value: 'Organic Farming' },
  { label: 'Agribusiness', value: 'Agribusiness' },

  // Other
  { label: 'Import/Export', value: 'Import/Export' },
  { label: 'Freelancer', value: 'Freelancer' },
  { label: 'Self-Employed', value: 'Self-Employed' },
  { label: 'Startup', value: 'Startup' },
  { label: 'Other', value: 'Other' },
];

export const KEYWORDS: FilterOption[] = [
  // Business & Growth
  { label: 'Scaling', value: 'Scaling' },
  { label: 'Growth', value: 'Growth' },
  { label: 'Expansion', value: 'Expansion' },
  { label: 'Innovation', value: 'Innovation' },
  { label: 'Digital Transformation', value: 'Digital Transformation' },
  { label: 'Entrepreneurship', value: 'Entrepreneurship' },
  { label: 'Business Development', value: 'Business Development' },
  { label: 'Strategy', value: 'Strategy' },
  { label: 'Optimization', value: 'Optimization' },
  { label: 'Efficiency', value: 'Efficiency' },
  { label: 'Revenue', value: 'Revenue' },
  { label: 'Profitability', value: 'Profitability' },
  { label: 'Market Share', value: 'Market Share' },
  { label: 'Competitive Advantage', value: 'Competitive Advantage' },
  { label: 'Customer Acquisition', value: 'Customer Acquisition' },
  { label: 'Customer Retention', value: 'Customer Retention' },
  { label: 'Brand Building', value: 'Brand Building' },
  { label: 'Market Penetration', value: 'Market Penetration' },
  { label: 'Diversification', value: 'Diversification' },
  { label: 'New Markets', value: 'New Markets' },

  // Technology & Digital
  { label: 'AI/Machine Learning', value: 'AI' },
  { label: 'Automation', value: 'Automation' },
  { label: 'Cloud Migration', value: 'Cloud Migration' },
  { label: 'Data Analytics', value: 'Data Analytics' },
  { label: 'Big Data', value: 'Big Data' },
  { label: 'IoT', value: 'IoT' },
  { label: 'Blockchain', value: 'Blockchain' },
  { label: 'Cybersecurity', value: 'Cybersecurity' },
  { label: 'Digital Marketing', value: 'Digital Marketing' },
  { label: 'Social Media Marketing', value: 'Social Media Marketing' },
  { label: 'Email Marketing', value: 'Email Marketing' },
  { label: 'SEO', value: 'SEO' },
  { label: 'Content Marketing', value: 'Content Marketing' },
  { label: 'Influencer Marketing', value: 'Influencer Marketing' },
  { label: 'Paid Advertising', value: 'Paid Advertising' },
  { label: 'Website Optimization', value: 'Website Optimization' },
  { label: 'Mobile App', value: 'Mobile App' },
  { label: 'Web Platform', value: 'Web Platform' },
  { label: 'SaaS Model', value: 'SaaS Model' },

  // Sales & Marketing
  { label: 'Lead Generation', value: 'Lead Generation' },
  { label: 'Sales Pipeline', value: 'Sales Pipeline' },
  { label: 'B2B Sales', value: 'B2B Sales' },
  { label: 'B2C Sales', value: 'B2C Sales' },
  { label: 'Sales Training', value: 'Sales Training' },
  { label: 'Conversion Rate', value: 'Conversion Rate' },
  { label: 'CRM', value: 'CRM' },
  { label: 'Marketing Automation', value: 'Marketing Automation' },
  { label: 'Customer Experience', value: 'Customer Experience' },
  { label: 'User Experience', value: 'User Experience' },
  { label: 'Branding', value: 'Branding' },
  { label: 'Public Relations', value: 'Public Relations' },
  { label: 'Partnership', value: 'Partnership' },
  { label: 'Joint Venture', value: 'Joint Venture' },

  // Operations & Management
  { label: 'Process Improvement', value: 'Process Improvement' },
  { label: 'Lean Management', value: 'Lean Management' },
  { label: 'Six Sigma', value: 'Six Sigma' },
  { label: 'Supply Chain', value: 'Supply Chain' },
  { label: 'Inventory Management', value: 'Inventory Management' },
  { label: 'Quality Assurance', value: 'Quality Assurance' },
  { label: 'Project Management', value: 'Project Management' },
  { label: 'Agile', value: 'Agile' },
  { label: 'Scrum', value: 'Scrum' },
  { label: 'Resource Planning', value: 'Resource Planning' },
  { label: 'Team Management', value: 'Team Management' },
  { label: 'Leadership', value: 'Leadership' },
  { label: 'Change Management', value: 'Change Management' },
  { label: 'Risk Management', value: 'Risk Management' },

  // Finance & Compliance
  { label: 'Financial Planning', value: 'Financial Planning' },
  { label: 'Budgeting', value: 'Budgeting' },
  { label: 'Accounting', value: 'Accounting' },
  { label: 'Internal Audit', value: 'Internal Audit' },
  { label: 'Compliance', value: 'Compliance' },
  { label: 'Regulatory', value: 'Regulatory' },
  { label: 'Tax Planning', value: 'Tax Planning' },
  { label: 'Funding', value: 'Funding' },
  { label: 'Investor Relations', value: 'Investor Relations' },
  { label: 'M&A', value: 'M&A' },
  { label: 'Valuation', value: 'Valuation' },

  // Human Resources
  { label: 'Recruitment', value: 'Recruitment' },
  { label: 'Talent Management', value: 'Talent Management' },
  { label: 'Employee Engagement', value: 'Employee Engagement' },
  { label: 'Training & Development', value: 'Training & Development' },
  { label: 'Performance Management', value: 'Performance Management' },
  { label: 'Compensation', value: 'Compensation' },
  { label: 'Benefits', value: 'Benefits' },
  { label: 'Diversity & Inclusion', value: 'Diversity & Inclusion' },
  { label: 'Culture', value: 'Culture' },
  { label: 'Remote Work', value: 'Remote Work' },

  // Health & Wellness Industry
  { label: 'Fitness Programs', value: 'Fitness Programs' },
  { label: 'Nutrition Coaching', value: 'Nutrition Coaching' },
  { label: 'Health Coaching', value: 'Health Coaching' },
  { label: 'Wellness Programs', value: 'Wellness Programs' },
  { label: 'Mental Health Support', value: 'Mental Health Support' },
  { label: 'Stress Management', value: 'Stress Management' },
  { label: 'Work-Life Balance', value: 'Work-Life Balance' },
  { label: 'Sleep Optimization', value: 'Sleep Optimization' },
  { label: 'Holistic Health', value: 'Holistic Health' },
  { label: 'Preventive Health', value: 'Preventive Health' },

  // Sustainability
  { label: 'Sustainability', value: 'Sustainability' },
  { label: 'ESG', value: 'ESG' },
  { label: 'Green Business', value: 'Green Business' },
  { label: 'Carbon Neutral', value: 'Carbon Neutral' },
  { label: 'Eco-Friendly', value: 'Eco-Friendly' },

  // Industry Specific
  { label: 'E-commerce Growth', value: 'E-commerce Growth' },
  { label: 'Subscription Model', value: 'Subscription Model' },
  { label: 'Marketplace', value: 'Marketplace' },
  { label: 'Franchising', value: 'Franchising' },
  { label: 'Licensing', value: 'Licensing' },
  { label: 'White Label', value: 'White Label' },
  { label: 'Dropshipping', value: 'Dropshipping' },
  { label: 'Affiliate Marketing', value: 'Affiliate Marketing' },
];
